name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-18.04
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DB_USER: postgres
        DB_PASSWORD: postgres
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DJANGO_SYS_EMAIL: ${{ secrets.DJANGO_SYS_EMAIL }}
        DJANGO_SYS_EMAIL_PWD: ${{ secrets.DJANGO_SYS_EMAIL_PWD }}
      run: |
        docker-compose build --no-cache
        docker-compose up --force-recreate
